[[session]]
name = "Staging DB"
path = "~/Keikaku/work/db/"


[[session]]
name = "kawa 川"
path = "~/Keikaku/bokuno/kawa/"
startup_command = "just status"
windows = [ "frontend", "kawa-frontend-cli", "graphql-server"]

[[window]]
name = "frontend"
path = "~/Keikaku/bokuno/kawa/kawa-frontend/"
startup_command = "nvim ."

[[window]]
name = "frontend-cli"
path = "~/Keikaku/bokuno/kawa/kawa-frontend/"
startup_command = "bun dev"

[[window]]
name = "graphql-server"
path = "~/Keikaku/bokuno/kawa/kawa-api-gateway/"
