# Autogenerated by `bun2nix`, editing manually is not recommended
#
# Set of Bun packages to install
#
# Consume this with `fetchBunDeps` (recommended)
# or `pkgs.callPackage` if you wish to handle
# it manually.
{
  copyPathToStore,
  fetchFromGitHub,
  fetchgit,
  fetchurl,
  ...
}:
{
  "@mixmark-io/domino@2.2.0" = fetchurl {
    url = "https://registry.npmjs.org/@mixmark-io/domino/-/domino-2.2.0.tgz";
    hash = "sha512-Y28PR25bHXUg88kCV7nivXrP2Nj2RueZ3/l/jdx6J9f8J4nsEGcgX0Qe6lt7Pa+J79+kPiJU3LguR6O/6zrLOw==";
  };
  "@xmldom/xmldom@0.8.13" = fetchurl {
    url = "https://registry.npmjs.org/@xmldom/xmldom/-/xmldom-0.8.13.tgz";
    hash = "sha512-KRYzxepc14G/CEpEGc3Yn+JKaAeT63smlDr+vjB8jRfgTBBI9wRj/nkQEO+ucV8p8I9bfKLWp37uHgFrbntPvw==";
  };
  "boolbase@1.0.0" = fetchurl {
    url = "https://registry.npmjs.org/boolbase/-/boolbase-1.0.0.tgz";
    hash = "sha512-JZOSA7Mo9sNGB8+UjSgzdLtokWAky1zbztM3WRLCbZ70/3cTANmQmOdR7y2g+J0e2WXywy1yS468tY+IruqEww==";
  };
  "commander@12.1.0" = fetchurl {
    url = "https://registry.npmjs.org/commander/-/commander-12.1.0.tgz";
    hash = "sha512-Vw8qHK3bZM9y/P10u3Vib8o/DdkvA2OtPtZvD871QKjy74Wj1WSKFILMPRPSdUSx5RFK1arlJzEtA4PkFgnbuA==";
  };
  "css-select@5.2.2" = fetchurl {
    url = "https://registry.npmjs.org/css-select/-/css-select-5.2.2.tgz";
    hash = "sha512-TizTzUddG/xYLA3NXodFM0fSbNizXjOKhqiQQwvhlspadZokn1KDy0NZFS0wuEubIYAV5/c1/lAr0TaaFXEXzw==";
  };
  "css-what@6.2.2" = fetchurl {
    url = "https://registry.npmjs.org/css-what/-/css-what-6.2.2.tgz";
    hash = "sha512-u/O3vwbptzhMs3L1fQE82ZSLHQQfto5gyZzwteVIEyeaY5Fc7R4dapF/BvRoSYFeqfBk4m0V1Vafq5Pjv25wvA==";
  };
  "cssom@0.5.0" = fetchurl {
    url = "https://registry.npmjs.org/cssom/-/cssom-0.5.0.tgz";
    hash = "sha512-iKuQcq+NdHqlAcwUY0o/HL69XQrUaQdMjmStJ8JFmUaiiQErlhrmuigkg/CU4E2J0IyUKUrMAgl36TvN67MqTw==";
  };
  "dom-serializer@2.0.0" = fetchurl {
    url = "https://registry.npmjs.org/dom-serializer/-/dom-serializer-2.0.0.tgz";
    hash = "sha512-wIkAryiqt/nV5EQKqQpo3SToSOV9J0DnbJqwK7Wv/Trc92zIAYZ4FlMu+JPFW1DfGFt81ZTCGgDEabffXeLyJg==";
  };
  "domelementtype@2.3.0" = fetchurl {
    url = "https://registry.npmjs.org/domelementtype/-/domelementtype-2.3.0.tgz";
    hash = "sha512-OLETBj6w0OsagBwdXnPdN0cnMfF9opN69co+7ZrbfPGrdpPVNBUj02spi6B1N7wChLQiPn4CSH/zJvXw56gmHw==";
  };
  "domhandler@5.0.3" = fetchurl {
    url = "https://registry.npmjs.org/domhandler/-/domhandler-5.0.3.tgz";
    hash = "sha512-cgwlv/1iFQiFnU96XXgROh8xTeetsnJiDsTc7TYCLFd9+/WNkIqPTxiM/8pSd8VIrhXGTf1Ny1q1hquVqDJB5w==";
  };
  "domutils@3.2.2" = fetchurl {
    url = "https://registry.npmjs.org/domutils/-/domutils-3.2.2.tgz";
    hash = "sha512-6kZKyUajlDuqlHKVX1w7gyslj9MPIXzIFiz/rGu35uC1wMi+kMhQwGhl4lt9unC9Vb9INnY9Z3/ZA3+FhASLaw==";
  };
  "entities@4.5.0" = fetchurl {
    url = "https://registry.npmjs.org/entities/-/entities-4.5.0.tgz";
    hash = "sha512-V0hjH4dGPh9Ao5p0MoRY6BVqtwCjhz6vI5LT8AJ55H+4g9/4vbHx1I54fS0XuclLhDHArPQCiMjDxjaL8fPxhw==";
  };
  "entities@7.0.1" = fetchurl {
    url = "https://registry.npmjs.org/entities/-/entities-7.0.1.tgz";
    hash = "sha512-TWrgLOFUQTH994YUyl1yT4uyavY5nNB5muff+RtWaqNVCAK408b5ZnnbNAUEWLTCpum9w6arT70i1XdQ4UeOPA==";
  };
  "html-escaper@3.0.3" = fetchurl {
    url = "https://registry.npmjs.org/html-escaper/-/html-escaper-3.0.3.tgz";
    hash = "sha512-RuMffC89BOWQoY0WKGpIhn5gX3iI54O6nRA0yC124NYVtzjmFWBIiFd8M0x+ZdX0P9R4lADg1mgP8C7PxGOWuQ==";
  };
  "htmlparser2@10.1.0" = fetchurl {
    url = "https://registry.npmjs.org/htmlparser2/-/htmlparser2-10.1.0.tgz";
    hash = "sha512-VTZkM9GWRAtEpveh7MSF6SjjrpNVNNVJfFup7xTY3UpFtm67foy9HDVXneLtFVt4pMz5kZtgNcvCniNFb1hlEQ==";
  };
  "linkedom@0.18.12" = fetchurl {
    url = "https://registry.npmjs.org/linkedom/-/linkedom-0.18.12.tgz";
    hash = "sha512-jalJsOwIKuQJSeTvsgzPe9iJzyfVaEJiEXl+25EkKevsULHvMJzpNqwvj1jOESWdmgKDiXObyjOYwlUqG7wo1Q==";
  };
  "mathml-to-latex@1.5.0" = fetchurl {
    url = "https://registry.npmjs.org/mathml-to-latex/-/mathml-to-latex-1.5.0.tgz";
    hash = "sha512-rrWn0eEvcEcdMM4xfHcSGIy+i01DX9byOdXTLWg+w1iJ6O6ohP5UXY1dVzNUZLhzfl3EGcRekWLhY7JT5Omaew==";
  };
  "nth-check@2.1.1" = fetchurl {
    url = "https://registry.npmjs.org/nth-check/-/nth-check-2.1.1.tgz";
    hash = "sha512-lqjrjmaOoAnWfMmBPL+XNnynZh2+swxiX3WUE0s4yEHI6m+AwrK2UZOimIRl3X/4QctVqS8AiZjFqyOGrMXb/w==";
  };
  "temml@0.13.2" = fetchurl {
    url = "https://registry.npmjs.org/temml/-/temml-0.13.2.tgz";
    hash = "sha512-n8fDRSsLscq9nh9j6z+FgkCvFMT0IJm6GCgwfzh+7AHT3Sfb4jFTQlsA6hVcF2dYYr3b66oDBVES95RfoukyrA==";
  };
  "turndown@7.2.4" = fetchurl {
    url = "https://registry.npmjs.org/turndown/-/turndown-7.2.4.tgz";
    hash = "sha512-I8yFsfRzmzK0WV1pNNOA4A7y4RDfFxPRxb3t+e3ui14qSGOxGtiSP6GjeX+Y6CHb7HYaFj7ECUD7VE5kQMZWGQ==";
  };
  "uhyphen@0.2.0" = fetchurl {
    url = "https://registry.npmjs.org/uhyphen/-/uhyphen-0.2.0.tgz";
    hash = "sha512-qz3o9CHXmJJPGBdqzab7qAYuW8kQGKNEuoHFYrBwV6hWIMcpAmxDLXojcHfFr9US1Pe6zUswEIJIbLI610fuqA==";
  };
}